"""fix appointment therapist foreign key

Revision ID: 5a0a4756d7ea
Revises: 42c0994894e1
Create Date: 2026-09-27 22:11:31.619710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0a4756d7ea'
down_revision = '42c0994894e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('booking_id', sa.String(length=20), nullable=False))
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_service_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_therapist_id'), table_name='appointments')
    op.create_index(op.f('ix_appointments_booking_id'), 'appointments', ['booking_id'], unique=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'notes')
    op.drop_column('appointments', 'start_time')
    op.drop_column('appointments', 'therapist_id')
    op.drop_column('appointments', 'created_at')
    op.drop_column('appointments', 'reason')
    op.drop_column('appointments', 'status')
    op.drop_column('appointments', 'end_time')
    op.drop_column('appointments', 'appointment_date')
    op.drop_column('appointments', 'service_id')
    op.drop_column('appointments', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('created_by', sa.INTEGER(), nullable=True))
    op.add_column('appointments', sa.Column('service_id', sa.INTEGER(), nullable=True))
    op.add_column('appointments', sa.Column('appointment_date', sa.DATE(), nullable=False))
    op.add_column('appointments', sa.Column('end_time', sa.VARCHAR(length=20), nullable=False))
    op.add_column('appointments', sa.Column('status', sa.VARCHAR(length=30), nullable=False))
    op.add_column('appointments', sa.Column('reason', sa.TEXT(), nullable=True))
    op.add_column('appointments', sa.Column('created_at', sa.DATETIME(), nullable=False))
    op.add_column('appointments', sa.Column('therapist_id', sa.INTEGER(), nullable=False))
    op.add_column('appointments', sa.Column('start_time', sa.VARCHAR(length=20), nullable=False))
    op.add_column('appointments', sa.Column('notes', sa.TEXT(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'appointments', 'therapists', ['therapist_id'], ['id'])
    op.drop_index(op.f('ix_appointments_booking_id'), table_name='appointments')
    op.create_index(op.f('ix_appointments_therapist_id'), 'appointments', ['therapist_id'], unique=False)
    op.create_index(op.f('ix_appointments_service_id'), 'appointments', ['service_id'], unique=False)
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.drop_column('appointments', 'booking_id')
    # ### end Alembic commands ###
