"""add payment method to invoices

Revision ID: c346c15e1694
Revises: b7c4e6a1d2f3
Create Date: 2026-09-28 11:56:43.797041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c346c15e1694'
down_revision = 'b7c4e6a1d2f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
