"""migrate

Revision ID: 522960690b86
Revises: 001_initial_schema
Create Date: 2026-09-25 11:49:40.425010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522960690b86'
down_revision = '001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_therapist_id'), 'appointments', ['therapist_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'users', ['created_by'], ['id'])
    op.drop_column('appointments', 'payment_method')
    op.add_column('invoices', sa.Column('invoice_number', sa.String(length=50), nullable=False))
    op.add_column('invoices', sa.Column('appointment_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False))
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_patient_id'), 'invoices', ['patient_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'appointments', ['appointment_id'], ['id'])
    op.drop_column('invoices', 'service')
    op.drop_column('invoices', 'payment_method')
    op.drop_column('invoices', 'amount')
    op.add_column('patients', sa.Column('first_name', sa.String(length=80), nullable=False))
    op.add_column('patients', sa.Column('last_name', sa.String(length=80), nullable=False))
    op.add_column('patients', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('patients', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('patients', sa.Column('blood_group', sa.String(length=10), nullable=True))
    op.add_column('patients', sa.Column('allergies', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('medical_notes', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('patients', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('patients', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_column('patients', 'condition')
    op.drop_column('patients', 'package')
    op.drop_column('patients', 'name')
    op.drop_column('patients', 'age')
    op.add_column('therapists', sa.Column('license_number', sa.String(length=100), nullable=True))
    op.add_column('therapists', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('therapists', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'therapists', ['license_number'])
    op.add_column('users', sa.Column('first_name', sa.String(length=80), nullable=False))
    op.add_column('users', sa.Column('middle_name', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=80), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'first_name')
    op.drop_constraint(None, 'therapists', type_='unique')
    op.drop_column('therapists', 'email')
    op.drop_column('therapists', 'phone')
    op.drop_column('therapists', 'license_number')
    op.add_column('patients', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('package', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('condition', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.alter_column('patients', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('patients', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('patients', 'is_active')
    op.drop_column('patients', 'medical_notes')
    op.drop_column('patients', 'allergies')
    op.drop_column('patients', 'blood_group')
    op.drop_column('patients', 'email')
    op.drop_column('patients', 'date_of_birth')
    op.drop_column('patients', 'last_name')
    op.drop_column('patients', 'first_name')
    op.add_column('invoices', sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('payment_method', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('service', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_patient_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_column('invoices', 'total')
    op.drop_column('invoices', 'tax')
    op.drop_column('invoices', 'subtotal')
    op.drop_column('invoices', 'appointment_id')
    op.drop_column('invoices', 'invoice_number')
    op.add_column('appointments', sa.Column('payment_method', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_therapist_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_column('appointments', 'is_deleted')
    op.drop_column('appointments', 'created_by')
    op.drop_column('appointments', 'reason')
    # ### end Alembic commands ###
